re-init ISABELLE_PROCESS_OPTIONS to allow nested ISABELLE_PROCESS invocations, e.g. HOL-Mutabelle-ex;

diff --git a/bin/isabelle-process b/bin/isabelle-process
--- a/bin/isabelle-process
+++ b/bin/isabelle-process
@@ -222,10 +222,8 @@ elif [ -n "$WRAPPER_FIFOS" ]; then
   [ -p "${FIFOS[1]}" ] || fail "Bad output fifo: ${FIFOS[1]}"
   MLTEXT="$MLTEXT; Isabelle_Process.init_fifos \"${FIFOS[0]}\" \"${FIFOS[1]}\";"
 else
-  if [ -z "$ISABELLE_PROCESS_OPTIONS" ]; then
-    ISABELLE_PROCESS_OPTIONS="$ISABELLE_TMP/options"
-    "$ISABELLE_TOOL" options -x "$ISABELLE_PROCESS_OPTIONS" || fail "Failed to retrieve options"
-  fi
+  ISABELLE_PROCESS_OPTIONS="$ISABELLE_TMP/options"
+  "$ISABELLE_TOOL" options -x "$ISABELLE_PROCESS_OPTIONS" || fail "Failed to retrieve options"
   if [ "$INPUT" != RAW_ML_SYSTEM ]; then
     MLTEXT="Options.load_default () handle _ => exit 2; $MLTEXT"
   fi
