prefer curl: presumably more portable and versatile;

diff --git a/Admin/lib/Tools/makedist_bundle b/Admin/lib/Tools/makedist_bundle
--- a/Admin/lib/Tools/makedist_bundle
+++ b/Admin/lib/Tools/makedist_bundle
@@ -113,9 +113,11 @@ do
                 echo "  component $COMPONENT"
                 CONTRIB="$ARCHIVE_DIR/contrib/${COMPONENT}.tar.gz"
                 if [ ! -f "$CONTRIB" ]; then
+                  type -p curl  > /dev/null || fail "Cannot download files: missing curl"
                   REMOTE="$ISABELLE_COMPONENT_REPOSITORY/${COMPONENT}.tar.gz"
-                  echo "  download $REMOTE"
-                  perl -MLWP::Simple -e "getprint '$REMOTE';" > "$CONTRIB"
+                  echo "  downloading $REMOTE"
+                  curl --fail --silent "$REMOTE" > "$CONTRIB" || \
+                    fail "Failed to download \"$REMOTE\""
                   perl -e "exit((stat('${CONTRIB}'))[7] == 0 ? 0 : 1);" && exit 2
                 fi
 
diff --git a/lib/Tools/components b/lib/Tools/components
--- a/lib/Tools/components
+++ b/lib/Tools/components
@@ -124,9 +124,11 @@ else
     else
       if [ ! -e "${FULL_NAME}.tar.gz" ]; then
         REMOTE="$COMPONENT_REPOSITORY/${BASE_NAME}.tar.gz"
+        type -p curl > /dev/null || fail "Cannot download files: missing curl"
         echo "Getting \"$REMOTE\""
         mkdir -p "$(dirname "$FULL_NAME")"
-        perl -MLWP::Simple -e "getprint '$REMOTE';" > "${FULL_NAME}.tar.gz"
+        curl --fail --silent "$REMOTE" > "${FULL_NAME}.tar.gz" || \
+          fail "Failed to download \"$REMOTE\""
         if perl -e "exit((stat('${FULL_NAME}.tar.gz'))[7] == 0 ? 0 : 1);"
         then
           rm -f "${FULL_NAME}.tar.gz"
