unconditional jedit_build; less intrusive build_doc;

diff --git a/Admin/lib/Tools/makedist b/Admin/lib/Tools/makedist
--- a/Admin/lib/Tools/makedist
+++ b/Admin/lib/Tools/makedist
@@ -170,17 +170,14 @@ find . -print | xargs chmod -f u+rw
 ./bin/isabelle env ISABELLE_SCALA_BUILD_OPTIONS="$ISABELLE_SCALA_BUILD_OPTIONS -optimise" \
   ./Admin/build all || fail "Failed to build distribution"
 
-if [ -n "$ISABELLE_JEDIT_BUILD_HOME" ]; then
-  ./bin/isabelle env ISABELLE_SCALA_BUILD_OPTIONS="$ISABELLE_SCALA_BUILD_OPTIONS -optimise" \
-    ./bin/isabelle jedit -b || fail "Failed to build Isabelle/jEdit"
-else
-  echo "### Missing jEdit build component"
-fi
+./bin/isabelle env ISABELLE_SCALA_BUILD_OPTIONS="$ISABELLE_SCALA_BUILD_OPTIONS -optimise" \
+  ./bin/isabelle jedit -b || fail "Failed to build Isabelle/jEdit"
 
-cp -a src/Doc src/Doc.orig
-./bin/isabelle env ./bin/isabelle build_doc $JOBS -a || fail "Failed to build documentation"
-rm -rf src/Doc
-mv src/Doc.orig src/Doc
+cp -a src src.orig
+env ISABELLE_IDENTIFIER="${DISTNAME}-build" \
+  ./bin/isabelle build_doc $JOBS -a || fail "Failed to build documentation"
+rm -rf src
+mv src.orig src
 
 rm -rf Admin
 
