no attempt to build documentation for now -- requires ML_HOME etc. which is not present here;

diff --git a/Admin/Release/makedist b/Admin/Release/makedist
--- a/Admin/Release/makedist
+++ b/Admin/Release/makedist
@@ -150,7 +150,8 @@ perl -pi -e 's/^(ISABELLE_SCALA_BUILD_OPTIONS=")/$1-optimise /,' etc/settings
 ./Admin/build all || fail "Failed to build distribution"
 
 cp -a src/Doc src/Doc.orig
-./bin/isabelle build_doc -a || fail "Failed to build documentation"
+# FIXME
+# ./bin/isabelle build_doc -a || fail "Failed to build documentation"
 
 if [ -n "$ISABELLE_JEDIT_BUILD_HOME" ]; then
   [ -d "$ISABELLE_JEDIT_BUILD_HOME" ] || fail "Bad jedit_build component directory: \"$ISABELLE_JEDIT_BUILD_HOME\""
