replaced ISATOOL by ISABELLE_TOOL;

diff --git a/Admin/build b/Admin/build
--- a/Admin/build
+++ b/Admin/build
@@ -17,12 +17,12 @@ PATH="/home/scala/scala/bin:$PATH"
 ISABELLE_DIR="$(cd "$(dirname "$0")"; cd "$(pwd -P)"; cd ..; pwd)"
 
 if [ -d "$ISABELLE_DIR/Distribution" ]; then
-  ISATOOL="$ISABELLE_DIR/Distribution/bin/isatool"
+  ISABELLE_TOOL="$ISABELLE_DIR/Distribution/bin/isatool"
   ISABELLE_LIB="$ISABELLE_DIR/Distribution/lib"
   ISABELLE_SRC="$ISABELLE_DIR"
   ISABELLE_DOC_SRC="$ISABELLE_DIR/Doc"
 else
-  ISATOOL="$ISABELLE_DIR/bin/isatool"
+  ISABELLE_TOOL="$ISABELLE_DIR/bin/isatool"
   ISABELLE_LIB="$ISABELLE_DIR/lib"
   ISABELLE_SRC="$ISABELLE_DIR/src"
   ISABELLE_DOC_SRC="$ISABELLE_DIR/doc-src"
@@ -112,7 +112,7 @@ function build_jars ()
   type -p scalac >/dev/null || fail "Scala compiler unavailable"
 
   pushd "$ISABELLE_SRC/Pure" >/dev/null
-  "$ISATOOL" make jar || fail "Failed to build Pure.jar!"
+  "$ISABELLE_TOOL" make jar || fail "Failed to build Pure.jar!"
   popd >/dev/null
 
   if [ -d "$HOME/lib/jedit/current" ]; then
diff --git a/Admin/isatest/isatest-makeall b/Admin/isatest/isatest-makeall
--- a/Admin/isatest/isatest-makeall
+++ b/Admin/isatest/isatest-makeall
@@ -88,9 +88,9 @@ case $HOSTNAME in
         ;;
 esac
 
-ISATOOL="$DISTPREFIX/Isabelle/bin/isatool"
+ISABELLE_TOOL="$DISTPREFIX/Isabelle/bin/isatool"
 
-[ -x $ISATOOL ] || fail "Cannot run $ISATOOL"
+[ -x $ISABELLE_TOOL ] || fail "Cannot run $ISABELLE_TOOL"
 
 if [ "$1" = "-l" ]; then
   shift
@@ -98,12 +98,12 @@ if [ "$1" = "-l" ]; then
   LOGIC="$1"
   TARGETS="$2"
   shift 2
-  ISABELLE_HOME="$($ISATOOL getenv -b ISABELLE_HOME)"
+  ISABELLE_HOME="$($ISABELLE_TOOL getenv -b ISABELLE_HOME)"
   DIR="$ISABELLE_HOME/src/$LOGIC"
-  TOOL="$ISATOOL make $MFLAGS $TARGETS"
+  TOOL="$ISABELLE_TOOL make $MFLAGS $TARGETS"
 else
   DIR="."
-  TOOL="$ISATOOL makeall $MFLAGS all"
+  TOOL="$ISABELLE_TOOL makeall $MFLAGS all"
 fi
 
 # main test loop
