isabelle.jars: temporarily disabled, until isatest gets up-to-date java;

diff --git a/Admin/makedist b/Admin/makedist
--- a/Admin/makedist
+++ b/Admin/makedist
@@ -180,16 +180,17 @@ rmdir Distribution
 
 ( cd lib/browser; make; ) || fail "Failed to build graph browser!"
 
-( cd lib/classes; ./mk; )
-[ -f lib/classes/isabelle.jar ] || fail "Failed to build Isabelle process wrapper!"
-
-if type -p scalac >/dev/null
-then
-  ( cd lib/jedit/plugin; ./mk; )
-  [ -f lib/jedit/isabelle.jar ] || fail "Failed to build jEdit plugin!"
-else
-  echo "Warning: Scala unavailable -- skipping jEdit plugin"
-fi
+# FIXME temporarily disabled, until isatest gets up-to-date java
+#( cd lib/classes; ./mk; )
+#[ -f lib/classes/isabelle.jar ] || fail "Failed to build Isabelle process wrapper!"
+#
+#if type -p scalac >/dev/null
+#then
+#  ( cd lib/jedit/plugin; ./mk; )
+#  [ -f lib/jedit/isabelle.jar ] || fail "Failed to build jEdit plugin!"
+#else
+#  echo "Warning: Scala unavailable -- skipping jEdit plugin"
+#fi
 
 cp doc/isabelle*.eps lib/logo
 
