updated to jdk-8u11 (inactive);

diff --git a/Admin/java/build b/Admin/java/build
--- a/Admin/java/build
+++ b/Admin/java/build
@@ -11,8 +11,8 @@ function fail()
 
 ## parameters
 
-VERSION="7u60"
-FULL_VERSION="1.7.0_60"
+VERSION="8u11"
+FULL_VERSION="1.8.0_11"
 
 ARCHIVE_LINUX32="jdk-${VERSION}-linux-i586.tar.gz"
 ARCHIVE_LINUX64="jdk-${VERSION}-linux-x64.tar.gz"
@@ -48,7 +48,7 @@ cat >> "$DIR/etc/settings" << EOF
 
 case "\${ISABELLE_PLATFORM64:-\$ISABELLE_PLATFORM32}" in
   x86-darwin)
-    echo "### Java 1.7 unavailable on 32bit Macintosh!" >&2
+    echo "### Java unavailable on 32bit Macintosh!" >&2
     ;;
   x86_64-darwin)
     ISABELLE_JDK_HOME="\$COMPONENT/\$ISABELLE_PLATFORM64/Contents/Home"
@@ -62,7 +62,7 @@ if [ -n "\$ISABELLE_JDK_HOME" ]; then
   if [ -d "\$ISABELLE_JDK_HOME" ]; then
     ISABELLE_JAVA_EXT="\${ISABELLE_JDK_HOME}/jre/lib/ext"
   else
-    echo "### Missing Java 1.7 platform directory: \"\$ISABELLE_JDK_HOME\"" >&2
+    echo "### Missing Java platform directory: \"\$ISABELLE_JDK_HOME\"" >&2
     unset ISABELLE_JDK_HOME
   fi
 fi
