more portable -- accomodate MiKTeX on Windows;

diff --git a/lib/Tools/browser b/lib/Tools/browser
--- a/lib/Tools/browser
+++ b/lib/Tools/browser
@@ -93,7 +93,10 @@ if [ -n "$GRAPHFILE" ]; then
   RC="$?"
 
   if [ -n "$PDF" ]; then
-    "$ISABELLE_EPSTOPDF" "$OUTFILE" || fail "Failed to produce pdf output"
+    (
+      cd "$(dirname "$OUTFILE")"
+      "$ISABELLE_EPSTOPDF" "$(basename "$OUTFILE")" || fail "Failed to produce pdf output"
+    )
   fi
 
   rm -f "$PRIVATE_FILE"
