clarified errors;

diff --git a/lib/Tools/electron b/lib/Tools/electron
--- a/lib/Tools/electron
+++ b/lib/Tools/electron
@@ -4,4 +4,9 @@
 #
 # DESCRIPTION: run the Electron framework within the Isabelle environment
 
-exec "$ISABELLE_VSCODIUM_ELECTRON" "$@"
+if [ -z "$ISABELLE_VSCODIUM_ELECTRON" ]; then
+  echo '*** Undefined $ISABELLE_VSCODIUM_ELECTRON: missing "vscodium" component'
+  exit 2
+else
+  exec "$ISABELLE_VSCODIUM_ELECTRON" "$@"
+fi
diff --git a/lib/Tools/node b/lib/Tools/node
--- a/lib/Tools/node
+++ b/lib/Tools/node
@@ -4,5 +4,10 @@
 #
 # DESCRIPTION: run the Node.js framework within the Isabelle environment
 
-export ELECTRON_RUN_AS_NODE=1
-exec "$ISABELLE_VSCODIUM_ELECTRON" "$@"
+if [ -z "$ISABELLE_VSCODIUM_ELECTRON" ]; then
+  echo '*** Undefined $ISABELLE_VSCODIUM_ELECTRON: missing "vscodium" component'
+  exit 2
+else
+  export ELECTRON_RUN_AS_NODE=1
+  exec "$ISABELLE_VSCODIUM_ELECTRON" "$@"
+fi
