clarified errors;

diff --git a/lib/Tools/ghc b/lib/Tools/ghc
--- a/lib/Tools/ghc
+++ b/lib/Tools/ghc
@@ -4,9 +4,9 @@
 #
 # DESCRIPTION: invoke Glasgow Haskell Compiler within the Isabelle environment
 
-if [ -d "$ISABELLE_STACK_ROOT" ]; then
+if [ -d "$ISABELLE_STACK_ROOT" -a -n "$ISABELLE_GHC" ]; then
   isabelle_stack ghc -- "$@"
 else
+  echo "Cannot execute ghc: missing Isabelle GHC setup" >&2
   exit 127
 fi
-
diff --git a/lib/Tools/ghci b/lib/Tools/ghci
--- a/lib/Tools/ghci
+++ b/lib/Tools/ghci
@@ -4,8 +4,9 @@
 #
 # DESCRIPTION: invoke GHC interaction within the Isabelle environment
 
-if [ -d "$ISABELLE_STACK_ROOT" ]; then
+if [ -d "$ISABELLE_STACK_ROOT" -a -n "$ISABELLE_GHC" ]; then
   isabelle_stack ghci "$@"
 else
+  echo "Cannot execute ghci: missing Isabelle GHC setup" >&2
   exit 127
 fi
