more uniform (see 1722cc56d22e);

diff --git a/lib/Tools/ocaml b/lib/Tools/ocaml
--- a/lib/Tools/ocaml
+++ b/lib/Tools/ocaml
@@ -4,4 +4,10 @@
 #
 # DESCRIPTION: invoke OCaml within the Isabelle environment
 
-isabelle_opam config exec --switch "$ISABELLE_OCAML_VERSION" -- ocaml "$@"
+if [ -d "$ISABELLE_OPAM_ROOT" -a -n "$ISABELLE_OCAML" ]
+then
+  isabelle_opam config exec --switch "$ISABELLE_OCAML_VERSION" -- ocaml "$@"
+else
+  echo "Cannot execute ocaml: missing Isabelle OCaml setup" >&2
+  exit 127
+fi
diff --git a/lib/Tools/ocamlc b/lib/Tools/ocamlc
--- a/lib/Tools/ocamlc
+++ b/lib/Tools/ocamlc
@@ -4,4 +4,10 @@
 #
 # DESCRIPTION: invoke OCaml compiler within the Isabelle environment
 
-isabelle_opam config exec --switch "$ISABELLE_OCAML_VERSION" -- ocamlc "$@"
+if [ -d "$ISABELLE_OPAM_ROOT" -a -n "$ISABELLE_OCAMLC" ]
+then
+  isabelle_opam config exec --switch "$ISABELLE_OCAML_VERSION" -- ocamlc "$@"
+else
+  echo "Cannot execute ocamlc: missing Isabelle OCaml setup" >&2
+  exit 127
+fi
