init_component: require absolute path (when invoked by user scripts);

diff --git a/lib/scripts/getsettings b/lib/scripts/getsettings
--- a/lib/scripts/getsettings
+++ b/lib/scripts/getsettings
@@ -91,6 +91,13 @@ ISABELLE_COMPONENTS=""
 function init_component ()
 {
   local COMPONENT="$1"
+  case "$COMPONENT" in
+    /*) ;;
+    *)
+      echo >&2 "Absolute component path required: \"$COMPONENT\""
+      exit 2
+      ;;
+  esac
 
   if [ ! -d "$COMPONENT" ]; then
     echo >&2 "Bad Isabelle component: \"$COMPONENT\""
